all:
	g++ -o tpu CCode.cpp CDecode.cpp CExecute.cpp CRegister.cpp CMemory.cpp main.cpp

	./tpu 02_Test.bin 17

all2:
	g++ -o tpu CCode.cpp CDecode.cpp CExecute.cpp CRegister.cpp CMemory.cpp main.cpp

	./tpu 02_Test_ECC.bin 17
