#include <iostream>
#include <rpc/rpc.h>

#define _RPCGEN_CLNT        // select client function prototype
#include "msg.h"            // generated by rpcgen

using namespace std;

int main( int argc, char* argv[] ) {
    CLIENT* clnt;
    int*    result;
    char*   server;
    char*   msg;

    if( argc != 3 ) {
        cerr << "Usage: " << argv[0] << " host message" << endl;
    }

    server  = argv[1];
    msg     = argv[2];

    /*
     * Create client "handle" used for
     * calling MESSAGEPROG on the server
     * designated on the command line.
     */
    clnt    = clnt_create( server, MESSAGEPROG, MESSAGEVERS, "tcp");

    if( clnt == (CLIENT*)NULL ) {
        /* Cannot extablish connection with server */
        clnt_pcreateerror(server);
        exit(1);
    }
    // Call the remote procedure "printmessage" on the server
    result = printmessage_1(&msg, clnt);
    if( result == (int*)NULL ) {
        // An error occured while calling the server
        clnt_perror(clnt, server);
        exit(1);
    }

    if( *result == 0 ) {
        // server was unable to print client's message
        cerr << argv[0] << ": could not print your message" << endl;
        exit(1);
    }

    // message printed on the server's console
    cout << "Message deliverd to " << server << endl;
    clnt_destroy( clnt );
    return 0;
}
