#include <iostream>
#include <fstream>
#include <rpc/rpc.h>
#include <stdlib.h>
#define _RPCGEN_SVC     // select server function
#include "msg.h"        // generated by rpcgen
//#include <Python.h>


using namespace std;

int*    printmessage_1( char** msg, CLIENT* UNUSED ) {
    static int  result;
    ofstream    f;

    f.open("rpc.log");
    if( f.is_open() == 0 ) {
        result = 0;
        return (&result);
    }
    f << *msg << endl;
    cout << "Hey, delivered data is \"" << *msg << "\"" << endl;
    int ret = system("python test.py");
    f.close();
    result = 1;
    return (&result);
}
//message func
int*    printmessage_1_svc( char** msg, struct svc_req* UNUSED ) {
    static int  result;
    ofstream    f;

    f.open("rpc.log");
    if( f.is_open() == 0 ) {
        result = 0;
        return (&result);
    }
    f << *msg << endl;
    if (strcmp(*msg, "1")==0)
        int ret = system("python test.py");
    else
        int ret = system("python test1.py");
    cout << "Hey, delivered data is \"" << *msg << "\"" << endl;
    f.close();
    
    result = 1;
    return (&result);
}
