/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include "IfxVadc_reg.h"
#include <def.h>

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
// SCU registers
#define LCK_BIT_LSB_IDX         1
#define ENDINIT_BIT_LSB_IDX     0
/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
IfxCpu_syncEvent g_cpuSyncEvent = 0;

uint16 adcResult;
uint16 arr_1[MAX_ARR_SIZE] = {0};
uint16 arr_2[MAX_ARR_SIZE] = {0};

// 0 -> arr_1 , 1 -> arr_2
uint8 flag_adc_bank = 0;
/*********************************************************************************************************************/
/*---------------------------------------------Function Prototypes---------------------------------------------------*/
/*********************************************************************************************************************/
void initVADC(void);
void VADC_startConversion(void);
uint16 VADC_readResult(void);

/*********************************************************************************************************************/
/*---------------------------------------------Interrupt Callbacks---------------------------------------------------*/
/*********************************************************************************************************************/


/*********************************************************************************************************************/
/*---------------------------------------------Main------------------------------------------------------------------*/
/*********************************************************************************************************************/
int core0_main(void)
{
    IfxCpu_enableInterrupts();
    
    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());
    
    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);

    initVADC();

    uint16 arr_idx = 0;

    while(1)
    {
        for(uint32 i = 0; i < 100000; i++);

        VADC_startConversion();
        adcResult = VADC_readResult();

        if( flag_adc_bank == 0 ) {  // arr_1
            arr_1[arr_idx] = adcResult;
        } else {                    // arr_2
            arr_2[arr_idx] = adcResult;
        }

        if( arr_idx == (MAX_ARR_SIZE-1) ) {
            arr_idx = 0;
            flag_adc_bank ^= 1;
        } else {
            arr_idx++;
        }
    }
    return (1);
}
/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
/* This function initializes the ASCLIN UART module */
void initVADC(void)
{
    // Password Access to unlock SCU_WDTSCON0
    SCU_WDTCPU0_CON0.U = ((SCU_WDTCPU0_CON0.U ^ 0xFC) & ~(1 << LCK_BIT_LSB_IDX)) | (1 << ENDINIT_BIT_LSB_IDX);
    while((SCU_WDTCPU0_CON0.U & (1 << LCK_BIT_LSB_IDX)) != 0);    // wait until unlocked
    // Modify Access to clear ENDINIT
    SCU_WDTCPU0_CON0.U = ((SCU_WDTCPU0_CON0.U ^ 0xFC) | (1 << LCK_BIT_LSB_IDX)) & ~(1 << ENDINIT_BIT_LSB_IDX);
    while((SCU_WDTCPU0_CON0.U & (1 << LCK_BIT_LSB_IDX)) == 0);    // wait until locked

    VADC_CLC.B.DISR = 0x0;  // enable VADC

    // Password Access to unlock SCU_WDTSCON0
    SCU_WDTCPU0_CON0.U = ((SCU_WDTCPU0_CON0.U ^ 0xFC) & ~(1 << LCK_BIT_LSB_IDX)) | (1 << ENDINIT_BIT_LSB_IDX);
    while((SCU_WDTCPU0_CON0.U & (1 << LCK_BIT_LSB_IDX)) != 0);    // wait until unlocked
    // Modify Access to set ENDINIT
    SCU_WDTCPU0_CON0.U = ((SCU_WDTCPU0_CON0.U ^ 0xFC) | (1 << LCK_BIT_LSB_IDX)) | (1 << ENDINIT_BIT_LSB_IDX);
    while((SCU_WDTCPU0_CON0.U & (1 << LCK_BIT_LSB_IDX)) == 0);

    // VADC configurations
    while(VADC_CLC.B.DISS != 0); // wait until VADC module enabled

    VADC_G4_ARBPR.B.PRIO0 = 0x3;        // highest priority for Request Source 0
    VADC_G4_ARBPR.B.CSM0 = 0x0;         // Wait-for-Start Mode
    VADC_G4_ARBPR.B.ASEN0 = 0x1;        // Arbitration Source Input 0 Enable
    VADC_G4_QMR0.B.ENGT = 0x1;          // enable conversion request
    VADC_G4_QMR0.B.FLUSH = 0x1;         // clear ADC queue
    VADC_G4_ARBCFG.B.ANONC = 0x3;       // ADC normal operation
    VADC_G4_ICLASS0.B.CMS = 0x0;        // Class 0 Standard Conversion (12-bit)

    // VADC Group 4 Channel 7 configuration
    VADC_G4_CHCTR7.B.RESPOS = 0x1;      // result right-aligned
    VADC_G4_CHCTR7.B.RESREG = 0x0;      // store result @ Result Register G4RES0
    VADC_G4_CHCTR7.B.ICLSEL = 0x0;      // Class 0
    VADC_G4_CHASS.B.ASSCH7 = 0x1;
}

void VADC_startConversion(void)
{
    VADC_G4_QINR0.B.REQCHNR = 0x07;     // no. of Request Channel = 7
    VADC_G4_QMR0.B.TREV = 0x1;          // Generate Conversion Start Trigger Event
}

uint16 VADC_readResult(void)
{
    uint16 result;
    while( VADC_G4_RES0.B.VF == 0 );   // wait until read available
    result = VADC_G4_RES0.B.RESULT;    // read ADC value
    return result;
}
