/**********************************************************************************************************************
 * \file Cpu1_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include <def.h>

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
extern IfxCpu_syncEvent g_cpuSyncEvent;

float conv[] = {0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1};

extern uint16 arr_1[MAX_ARR_SIZE];
extern uint16 arr_2[MAX_ARR_SIZE];
float arr_3[MAX_ARR_SIZE + CONV_FILTER_SIZE - 1] = {0};
extern uint16 originArr[MAX_ARR_SIZE + CONV_FILTER_SIZE - 1];

extern uint8 flag_adc_bank;     // 0 -> arr_1 , 1 -> arr_2
uint8 pre_flag_adc_bank = 0;
uint8 flag_dsp_finish = 0;      // (arr_1) 0 -> busy , 1 -> finish

/*********************************************************************************************************************/
/*---------------------------------------------Function Prototypes---------------------------------------------------*/
/*********************************************************************************************************************/
float convFunc(uint16 idx, uint16* arr, float conv[]);
void initLED(void);
/*********************************************************************************************************************/
/*---------------------------------------------Interrupt Callbacks---------------------------------------------------*/
/*********************************************************************************************************************/


/*********************************************************************************************************************/
/*---------------------------------------------Main------------------------------------------------------------------*/
/*********************************************************************************************************************/
int core1_main(void)
{
    IfxCpu_enableInterrupts();
    
    /* !!WATCHDOG1 IS DISABLED HERE!!
     * Enable the watchdog and service it periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    
    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);

    initLED();
    pre_flag_adc_bank = flag_adc_bank;

    while(1)
    {
        while( pre_flag_adc_bank == flag_adc_bank );
        pre_flag_adc_bank = flag_adc_bank;

        flag_dsp_finish = 0;
        if( pre_flag_adc_bank ) {   // arr_2 busy -> arr_1 read
            for(uint16 i = 0; i < (MAX_ARR_SIZE + CONV_FILTER_SIZE - 1); i++) {
                arr_3[i] = convFunc(i, arr_1, conv);
                if( i >= CONV_FILTER_SIZE ) {
                    originArr[i - CONV_FILTER_SIZE] = arr_1[i - CONV_FILTER_SIZE];
                }
            }
        } else {                    // arr_1 busy -> arr_2 read
            for(uint16 i = 0; i < (MAX_ARR_SIZE + CONV_FILTER_SIZE - 1); i++) {
                arr_3[i] = convFunc(i, arr_2, conv);
                if( i >= CONV_FILTER_SIZE ) {
                    originArr[i - CONV_FILTER_SIZE] = arr_2[i - CONV_FILTER_SIZE];
                }
            }
        }
        flag_dsp_finish = 1;

        // DSP underrun debug trap
        if( pre_flag_adc_bank != flag_adc_bank ) {
            P10_OUT.B.P1 = 0x1;    // red
            while(1);
        }
    }
    return (1);
}

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
float convFunc(uint16 idx, uint16* arr, float conv[]) {
    float result = 0;

    for(uint8 j = ((idx < MAX_ARR_SIZE) ? 0 : idx-MAX_ARR_SIZE+1); j < ((idx < CONV_FILTER_SIZE) ? idx+1 : CONV_FILTER_SIZE); j++)
        result += conv[j] * *(arr+idx-j);

    if( idx < CONV_FILTER_SIZE - 1 ) {
        for(uint8 j = idx+1; j < CONV_FILTER_SIZE; j++)
            result += conv[j] * *(arr+idx);
    }

    return result;
}

void initLED(void)
{
    P10_IOCR0.B.PC1 = 0x10;     // set P10.1 push-pull general output
    P10_IOCR0.B.PC2 = 0x10;     // set P10.2 push-pull general output
}
